



#define DRBDLOCK_VOLUMENAME_MAX_LEN	260

#ifndef _DRBDLOCK_STRUCT_
#define _DRBDLOCK_STRUCT_

enum VOLUME_NAME_TYPE
{
	VOLUME_TYPE_LETTER,
	VOLUME_TYPE_GUID,
};

typedef struct _DRBDLOCK_VOLUME {
	enum VOLUME_NAME_TYPE volumeType;
	WCHAR volumeName[DRBDLOCK_VOLUMENAME_MAX_LEN];
}DRBDLOCK_VOLUME, *PDRBDLOCK_VOLUME;

#endif