

#define DRBDLOCK_DEVICE_OBJECT_NAME	L"\\Device\\DrbdLock"
#define DRBDLOCK_SYMLINK_NAME		L"\\DosDevices\\DrbdLock"
#define DRBDLOCK_CALLBACK_NAME		L"\\Callback\\DrbdLock"

#define DRBDLOCK_VOLUMENAME_MAX_LEN	260

enum VOLUME_NAME_TYPE
{
	VOLUME_TYPE_LETTER,
	VOLUME_TYPE_GUID,
};

typedef struct _DRBDLOCK_VOLUME {
	enum VOLUME_NAME_TYPE volumeType;
	WCHAR volumeName[DRBDLOCK_VOLUMENAME_MAX_LEN];
}DRBDLOCK_VOLUME, *PDRBDLOCK_VOLUME;