



#define DRBDLOCK_VOLUMENAME_MAX_LEN	260

#ifndef _DRBDLOCK_STRUCT_
#define _DRBDLOCK_STRUCT_

enum VOLUME_NAME_TYPE
{
	VOLUME_TYPE_LETTER,
	VOLUME_TYPE_GUID,
	VOLUME_TYPE_DEVICE_NAME,
	VOLUME_TYPE_DEVICE_OBJECT,
};

typedef struct _DRBDLOCK_VOLUME {
	enum VOLUME_NAME_TYPE volumeType;
	union
	{
		WCHAR volumeName[DRBDLOCK_VOLUMENAME_MAX_LEN];
		PVOID pVolumeObject;
	}volumeID;
	
}DRBDLOCK_VOLUME, *PDRBDLOCK_VOLUME;

#endif